### ISSUE TITLE
Support different base coin

### ISSUE THREAD

**Issue by jiwushi66** [beeb/pancaketrade#3]
Hi,
Congratulations, Love it!
Would you consider supporting swap against another base coin, like BUSD?

**Comment by beeb** [comment]
Hi there. At the moment the bot is hardcoded for BNB and only works for direct LPs on PancakeSwap.

A lot of work would be needed to port this to another base coin like BUSD, and a lot of tokens don't have a LP for BUSD.
Would you expect the bot to route the swap like on the official PancakeSwap UI, where it swaps between multiple pairs to bridge between token and BUSD, or would you only trade tokens that have a direct LP with BUSD?

**Comment by jiwushi66** [comment]
Thanks for your reply!

What I expect is the bot route the swap like on the official PancakeSwap UI.

**Comment by beeb** [comment]
Ok thanks for the clarification.

The bot is not meant as a replacement for the pancakeswap UI, and such a modification will not happen in the foreseeable future as it would require a lot of changes to the core structure of the bot.

It's always possible to manually swap BNB for other tokens in pancakeswap afterwards. Most tokens have a BNB pair, but very few have other pairs available.

I'll keep this open because it could be useful in the future, but it won't happen soon. Thanks for your suggestion!

**Comment by beeb** [comment]
Closed via https://github.com/beeb/pancaketrade/pull/25
