### ISSUE TITLE
Add feature: trailing SL in % from ATH since entry (refresh each X seconds)

### ISSUE THREAD

**Issue by alejandrobailo** [beeb/pancaketrade#43]
Hi, 
first of all, awesome work and thanks a lot!

I think would be fine to set a SL trailing of a x% under the maximum value of the token since the entry.

E.j. 

Entry 0.1
SL 10% 0.09
Trainling SL 5%
... 1h later
Value 0.3
SL 0.25

**Comment by beeb** [comment]
Hello,

I think what you want to do can be achieved with 2 orders like so:

- Order 1: stop loss 0.09
- Order 2: take profit with trailing stop loss 5%

Example 1:
Entry price 0.1
Price moves to 0.3 ATH since entry -> order 2 is monitoring
Price moves below 0.285 -> order 2 triggers (5% drop from ATH) -> sell

Example 2:
Entry price 0.1
Price moves down below 0.09 -> order 1 triggers -> sell

**Comment by alejandrobailo** [comment]
But as I understood, bot says: 

OK, I will sell when the price of TOKEN reaches x BNB per token.
Next, how much TOKEN do you want me to use for selling?
You can also use scientific notation like x or a percentage like 63%.
Current balance: x TOKEN

That means bot will sell when the Take profit will be reached, in your example 1 when 0.105

**Comment by beeb** [comment]
Okay I think this is just a matter of bad documentation and/or messages.

When trailing stop loss (tsl) is activated on a sell order, the order will only execute once the price drops by X% compared to the maximum price during the monitoring period. Monitoring period starts when the price goes above the price value from the order.

**Comment by beeb** [comment]
Keep in mind that the more tokens you have added or the slower the RPC you use, the more time the script will need to get all the token prices. So effectively it could be slower than the specified amount.
