### ISSUE TITLE
Add usd or busd for price when buying or selling

### ISSUE THREAD

**Issue by kotik1998** [beeb/pancaketrade#45]
Hello, is there any chance to change this to USD or BUSD
![Screenshot_20211108-182204_Plus](https://user-images.githubusercontent.com/23015769/140796797-6b785b9a-b637-4774-a3e3-fbf83c8e4bbc.jpg)

**Comment by beeb** [comment]
This is something that would require a lot of rework in the background. At the moment, all prices are checked in BNB per token as this used to be the most common pair for tokens on BSC, and the script used to only support swapping on these liquidity pairs (with BNB).

But since 0.6.x the script can use BUSD and USDT liquidity as well, so it could make sense to also specify order prices in dollars.

In case this is added, it will probably be a global toggle in the config file, to either always use BNB prices, or always use USD prices.

**Comment by beeb** [comment]
This feature is available as preview in the `develop` branch. Will add a couple more settings and features before releasing a new minor version.

**Comment by tralhossauro** [comment]
> This feature is available as preview in the `develop` branch. Will add a couple more settings and features before releasing a new minor version.

Hi Beeb!
Tks for all...
Any news about USD prices?
Tksssssssss

**Comment by beeb** [comment]
It's in testing, will release a new version very soon as I didn't encounter any bugs yet.

**Comment by beeb** [comment]
Closed by https://github.com/beeb/pancaketrade/releases/tag/v0.7.0
