### ISSUE TITLE
Menu status ordering

### ISSUE THREAD

**Issue by DigiTecK3D** [beeb/pancaketrade#5]
This is a small thing, but I went in on my local source copy and switched these menus around since I felt they make more sense this way. You would want to create an order before ever deleting an order and buy or sell before selling all. Just a personal ordering thing. Thank you!

![image](https://user-images.githubusercontent.com/5471872/120058365-f1e08e00-c00f-11eb-80f0-f9d1e84e3210.png)

**Comment by beeb** [comment]
Hey! You're with that this ordering makes more sense for the reading order, however as a personal choice, I chose to have the most dangerous operations on the left since I'm right-handed and use my phone a lot. But I understand that it's less logical and there is anyway a confirmation prompt for all operations. I'll think about it!

**Comment by DigiTecK3D** [comment]
😁 That does makes sense now when you put it like that, those operations can be dangerous. Then again clicking sell all is pretty dangerous operation to click on also. I haven’t run thru any of those operations but I guess just having a “are you sure confirmation on all of it” would protect those operations in case someone accidentally clicked them. But thanks for considering it, something I can just change on my end for my preference.
