### ISSUE TITLE
More % of trailing stop loss

### ISSUE THREAD

**Issue by jazzlifepro** [beeb/pancaketrade#92]
Hello genius!
thanks thanks and thanks for the program! It is very useful and works very well.
I would like to know how to modify or add a % trailing stop loss of 20% and 30% since I move in very volatile shits

**Comment by beeb** [comment]
Hey there! Thanks for the kind words!

As indicated into the message, you can write your value in percent as a text message and send it instead of using one of the buttons.

![Screenshot_2022-08-28-21-12-34-81_948cd9899890cbd5c2798760b2b95377](https://user-images.githubusercontent.com/703631/187090708-254f41a5-2abb-4c03-9f36-054fa74e4b80.jpg)

**Comment by jazzlifepro** [comment]
oooh is true! I had not noticed that. very thankss!
